title: Genevieve theme
description: Documentation and support for the Genevieve Shopify theme
remote_theme: just-the-docs/just-the-docs
url: https://chandlerallanarts.github.io
baseurl: /genevieve-docs
